### ISSUE TITLE
Backport critical fix in PollEvented from tokio crate

### ISSUE THREAD

**Issue by glebpom** [tokio-rs/tokio-core#317] opened 2018-03-23 13:48 UTC
Hi,

https://github.com/tokio-rs/tokio/pull/250 contains the critical fix in `PollEvented`. This fix should also be applied to `tokio-core` because this code was backported from `tokio` crate recently

**Comment by carllerche** [comment] 2018-03-23 15:56
Thanks for the reports. Have you verified that the issue is present here?

**Comment by glebpom** [comment] 2018-03-23 17:20
Absolutely. The missprint is in https://github.com/tokio-rs/tokio-core/blob/master/src/reactor/poll_evented2.rs
In fact, we have observed a high CPU usage on slow connections after upgrading to latest version

**Comment by carllerche** [comment] 2018-03-23 17:22
Thanks. I'll try to get that fix released in a bit.

**Closed as completed** 2018-03-23 18:42 UTC
