### ISSUE TITLE
TCP_KEEPINTVL / TCP_KEEPCNT missing

### ISSUE THREAD

**Issue by aep** [tokio-rs/tokio-core#323] opened 2018-04-21 11:34 UTC
tokio_core::net::TcpStream::set_keepalive only lets you set TCP_KEEPIDLE, which isn't particularly useful.

resorting to nix::setsockopt over raw_fd works of course, but i suspect people will be confused, since the behavior when not setting TCP_KEEPINTVL is non-obvious, unless you know posix internals.

**Comment by carllerche** [comment] 2018-04-25 16:11
Thanks for this. I'm going to close this issue as tokio-core is deprecated, but Tokio generally follows mio's API (which, in turn, follows std). So, since the issue is currently open on the mio repo, this is kind of a "dup".

**Closed as completed by carllerche** 2018-04-25 16:11 UTC
